package types

// Code generated by a throwaway harness that imports github.com/jakecoffman/cp/v2
// v2.4.0, the version the port is anchored to. DO NOT EDIT.
//
// main's go.mod never gains cp, so this file is what the harness printed:
// ordinary table-driven Go source depending on nothing. For each row the
// harness built the Shape on a fresh cp.NewBody(0, 0) — cp.NewCircle,
// cp.NewSegment, cp.NewBox2 (kept as cp's four direct vertices), or
// cp.NewPolyShape with the identity transform (which hulls, as the port's
// constructor does) — added it with Body.AddShape, called Shape.SetDensity, and
// printed Body.Mass, Body.Moment and Body.CenterOfGravity: the one-shape case of
// AccumulateMassFromShapes. Every number is printed at float64's shortest
// round-trip spelling, so it is cp's answer exactly.
//
// The test that drives it is in mass_test.go.

// cpMassCase is cp's answer for one Shape at one density. kind and verts are in
// the terms cpShape uses in cpcases_test.go.
type cpMassCase struct {
	name    string
	kind    string
	radius  float64
	density float64
	verts   [][2]float64
	mass    float64
	moment  float64
	cog     [2]float64
}

var cpMassCases = []cpMassCase{
	{"circle.offset", "circle", 0.5, 2.5, [][2]float64{{0.3, -0.2}}, 1.9634954084936207, 0.2454369260617026, [2]float64{0.3, -0.2}},
	{"circle.far", "circle", 1.25, 0.8, [][2]float64{{-3, 4}}, 3.926990816987242, 3.0679615757712826, [2]float64{-3, 4}},
	{"capsule", "segment", 0.18, 3, [][2]float64{{-0.75, 0.25}, {1.75, -0.25}}, 3.0588333432690313, 2.190850388336714, [2]float64{0.5, 0}},
	{"capsule.fat", "segment", 0.6, 1.5, [][2]float64{{2, 1}, {2.5, 3}}, 5.407255095994383, 5.442279126747748, [2]float64{2.25, 2}},
	{"tri", "poly", 0, 2, [][2]float64{{-0.6, -0.4}, {1.7, -0.5}, {0, 1.8}}, 5.12, 2.6567111111111115, [2]float64{0.36666666666666675, 0.30000000000000004}},
	{"tri.rounded", "poly", 0.1, 2, [][2]float64{{-0.6, -0.4}, {1.7, -0.5}, {0, 1.8}}, 6.6713505862833085, 3.461689693104784, [2]float64{0.36666666666666675, 0.30000000000000004}},
	{"quad.box", "box", 0, 1.2, [][2]float64{{0.5, -0.25}, {2.5, 0.75}}, 2.4, 1, [2]float64{1.5, 0.25}},
	{"quad.box.rounded", "box", 0.15, 1.2, [][2]float64{{0.5, -0.25}, {2.5, 0.75}}, 3.5648230016469244, 1.4853429173528852, [2]float64{1.5, 0.25}},
	{"quad", "poly", 0, 4, [][2]float64{{0, 0}, {3, 0.5}, {2.5, 2}, {-0.5, 1.5}}, 19, 18.604166666666664, [2]float64{1.25, 1}},
	{"quad.rounded", "poly", 0.25, 4, [][2]float64{{0, 0}, {3, 0.5}, {2.5, 2}, {-0.5, 1.5}}, 29.030438353864046, 28.42563755482521, [2]float64{1.25, 1}},
	{"hexagon", "poly", 0, 0.7, [][2]float64{{3, 1}, {2.5, 1.866}, {1.5, 1.866}, {1, 1}, {1.5, 0.134}, {2.5, 0.134}}, 1.8185999999999998, 0.7577277726666667, [2]float64{2, 1}},
	{"hexagon.rounded", "poly", 0.2, 0.7, [][2]float64{{3, 1}, {2.5, 1.866}, {1.5, 1.866}, {1, 1}, {1.5, 0.134}, {2.5, 0.134}}, 2.746552274164991, 1.14436321192984, [2]float64{2, 1}},
}
